module.exports = {
    leadsObject: {
        phone1: { type: String, default: null },
        email: { type: String, default: null },
        leadid: { type: String  },
        primary_lead_id: { type: Number },
        leadip: { type: String  },
        ref: { type: String  },
        xAuthentication: { type: String, default: null },
        title: { type: String, default: null },
        firstname: { type: String, default: null },
        lastname: { type: String, default: null },
        BankName: { type: String },
        LenderIDs: { type: String },
        address: { type: String, default: null },
        address1: { type: String, default: null },
        address2: { type: String, default: null },
        address3: { type: String, default: null },
        previous_address1: String,
        previous_address2: String,
        previous_address3: String,
        previous_address4: String,
        previous_address5: String,
        previous_postcode1: { type: String, default: null },
        previous_postcode2: { type: String, default: null },
        previous_postcode3: { type: String, default: null },
        previous_postcode4: { type: String, default: null },
        previous_postcode5: { type: String, default: null },
        previous_address1_line1: String,
        previous_address2_line1: String,
        previous_address3_line1: String,
        previous_address4_line1: String,
        previous_address5_line1: String,
        previous_address1_line2: String,
        previous_address2_line2: String,
        previous_address3_line2: String,
        previous_address4_line2: String,
        previous_address5_line2: String,
        previous_address1_line3: String,
        previous_address2_line3: String,
        previous_address3_line3: String,
        previous_address4_line3: String,
        previous_address5_line3: String,
        previous_address1_city: { type: String, default: null },
        previous_address2_city: { type: String, default: null },
        previous_address3_city: { type: String, default: null },
        previous_address4_city: { type: String, default: null },
        previous_address5_city: { type: String, default: null },
        previous_address1_province: { type: String, default: null },
        previous_address2_province: { type: String, default: null },
        previous_address3_province: { type: String, default: null },
        previous_address4_province: { type: String, default: null },
        previous_address5_province: { type: String, default: null },
        previous_address1_company: { type: String, default: null },
        previous_address2_company: { type: String, default: null },
        previous_address3_company: { type: String, default: null },
        previous_address4_company: { type: String, default: null },
        previous_address5_company: { type: String, default: null },
        previous_name: String,
        city: { type: String, default: null },
        CBN: { type: String },
        directLink: { type: String },
        pbaDirectLink: { type: String },
        directLinkExist: { type: Boolean, default: false },
        province: { type: String, default: null },
        country: { type: String, default: null },
        company: { type: String, default: null },
        zip: { type: String, default: null },
        dob_day: { type: String, default: null },
        dob_month: { type: String, default: null },
        dob_year: { type: String, default: null },
        dob: { type: String, default: null },
        DateOfBirth: { type: String, default: null },
        document_id: { type: String },
        lookupid: { type: String, default: null },
        pdf_url: { type: String  },
        lender_id_doc_order: { type: String, default: null },
        signature_src: { type: String },
        PostURL: { type: String, default: null },
        is_waypoint: { type: Number,  default: 0 },
        is_submit: { type: Number, default: 0 },
        page_visited: { type: Number, default: 0 },
        is_signed: { type: Number, default: 0 },
        is_paperPack: { type: Number, default: 0 },
        notes: { type: String, default: "" },
        is_paid: { type: Number, default: 0 },
        total_sign: { type: Number, default: 0},
        email_send_count: { type: Number, default: 0 },
        sms_send_count: { type: Number, default: 0 },
        isExpired: { type: Boolean, default: false },
        isLocked: { type: Boolean, default: false },
        isEmailSent: { type: Boolean, default: false },
        isSmsSent: { type: Boolean, default: false },
        unsubscribe: { type: Boolean, default: false },
        linkExpiryDate: { type: Date },
        signatureDate: { type: Date },
        other: [ { type: String, default: [] } ],
        created: { type: Date, default: Date.now() }
    }
}